<?php
return [
    [
        'id' => 'botoes_de_lula',
        'category' => 'cat_mollusks',
        'category_slug' => 'mollusks',
        'image' => '/assets/img/products/Botoes de lula-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'camarao_7b_limpo',
        'category' => 'cat_crustaceans',
        'category_slug' => 'crustaceans',
        'image' => '/assets/img/products/Camarao 7B limpo-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'camarao_santana_m_g_40_60',
        'category' => 'cat_crustaceans',
        'category_slug' => 'crustaceans',
        'image' => '/assets/img/products/Camarao Santana M_G 40_60-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'camarao_rosa_inteiro_11_15_maior',
        'category' => 'cat_crustaceans',
        'category_slug' => 'crustaceans',
        'image' => '/assets/img/products/Camarao rosa inteiro 11_15 maior-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'camarao_rosa_inteiro_16_20_menor',
        'category' => 'cat_crustaceans',
        'category_slug' => 'crustaceans',
        'image' => '/assets/img/products/Camarao rosa inteiro 16_20 menor-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'camarao_rosa_limpo_201_300',
        'category' => 'cat_crustaceans',
        'category_slug' => 'crustaceans',
        'image' => '/assets/img/products/Camarao rosa limpo 201_300-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'camarao_rosa_limpo_80_100',
        'category' => 'cat_crustaceans',
        'category_slug' => 'crustaceans',
        'image' => '/assets/img/products/Camarao rosa limpo 80_100-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'camarao_rosa_limpo_e_eviserado_2g_21_30',
        'category' => 'cat_crustaceans',
        'category_slug' => 'crustaceans',
        'image' => '/assets/img/products/Camarao rosa limpo e eviserado 2G 21_30-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'camarao_rosa_limpo_e_eviserado_3g_16_20',
        'category' => 'cat_crustaceans',
        'category_slug' => 'crustaceans',
        'image' => '/assets/img/products/Camarao rosa limpo e eviserado 3G 16_20-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'camarao_rosa_limpo_e_eviserado_m_50_60',
        'category' => 'cat_crustaceans',
        'category_slug' => 'crustaceans',
        'image' => '/assets/img/products/Camarao rosa limpo e eviserado M  50_60-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'camarao_vannamei_30_40',
        'category' => 'cat_crustaceans',
        'category_slug' => 'crustaceans',
        'image' => '/assets/img/products/Camarao vannamei 30_40-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'camarao_vannamei_51_60_p_d',
        'category' => 'cat_crustaceans',
        'category_slug' => 'crustaceans',
        'image' => '/assets/img/products/Camarao vannamei 51_60 P&D-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'camarao_vannamei_51_60_pud',
        'category' => 'cat_crustaceans',
        'category_slug' => 'crustaceans',
        'image' => '/assets/img/products/Camarao vannamei 51_60 PUD-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'camarao_vannamei_51_60_s_cabeca',
        'category' => 'cat_crustaceans',
        'category_slug' => 'crustaceans',
        'image' => '/assets/img/products/Camarao vannamei 51_60 S_cabeca-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'costela_de_tambaqui',
        'category' => 'cat_fresh_fish',
        'category_slug' => 'fresh_fish',
        'image' => '/assets/img/products/Costela de Tambaqui-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'file_pangassios_220_up',
        'category' => 'cat_fresh_fish',
        'category_slug' => 'fresh_fish',
        'image' => '/assets/img/products/Filé Pangassios 220 UP-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'file_de_abadeijo_500_1000',
        'category' => 'cat_fresh_fish',
        'category_slug' => 'fresh_fish',
        'image' => '/assets/img/products/Filé de Abadeijo 500_1000.webp',
        'badge' => null,
    ],
    [
        'id' => 'file_de_cambucu_600_1000',
        'category' => 'cat_fresh_fish',
        'category_slug' => 'fresh_fish',
        'image' => '/assets/img/products/Filé de Cambucu 600_1000-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'file_de_linguado_m',
        'category' => 'cat_fresh_fish',
        'category_slug' => 'fresh_fish',
        'image' => '/assets/img/products/Filé de Linguado M-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'file_de_pescada_amarela_1.5_3.5',
        'category' => 'cat_fresh_fish',
        'category_slug' => 'fresh_fish',
        'image' => '/assets/img/products/Filé de Pescada Amarela 1.5_3.5-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'file_de_pescada_branca_m',
        'category' => 'cat_fresh_fish',
        'category_slug' => 'fresh_fish',
        'image' => '/assets/img/products/Filé de Pescada branca M-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'file_de_robalo_1_2',
        'category' => 'cat_fresh_fish',
        'category_slug' => 'fresh_fish',
        'image' => '/assets/img/products/Filé de Robalo 1_2-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'file_de_salmao_4_5',
        'category' => 'cat_fresh_fish',
        'category_slug' => 'fresh_fish',
        'image' => '/assets/img/products/Filé de Salmao 4_5-c.webp',
        'badge' => null,
    ],
    [
        'id' => 'file_de_tilapia_180_250',
        'category' => 'cat_fresh_fish',
        'category_slug' => 'fresh_fish',
        'image' => '/assets/img/products/Filé de Tilapia 180_250-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'file_de_truta_g',
        'category' => 'cat_fresh_fish',
        'category_slug' => 'fresh_fish',
        'image' => '/assets/img/products/Filé de Truta G-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'lombo_saithe_300_400',
        'category' => 'cat_salted_fish',
        'category_slug' => 'salted_fish',
        'image' => '/assets/img/products/Lombo Saithe 300_400-d.webp',
        'badge' => null,
    ],
    [
        'id' => 'lombo_saithe_300_400',
        'category' => 'cat_salted_fish',
        'category_slug' => 'salted_fish',
        'image' => '/assets/img/products/Lombo Saithe 300_400.webp',
        'badge' => null,
    ],
    [
        'id' => 'lombo_de_atum_1.5_3.5',
        'category' => 'cat_fresh_fish',
        'category_slug' => 'fresh_fish',
        'image' => '/assets/img/products/Lombo de Atum 1.5_3.5-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'lombo_de_bacalhau_gadus_morhua_700_900',
        'category' => 'cat_salted_fish',
        'category_slug' => 'salted_fish',
        'image' => '/assets/img/products/Lombo de Bacalhau Gadus Morhua 700_900-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'lombo_de_meca_1_2',
        'category' => 'cat_fresh_fish',
        'category_slug' => 'fresh_fish',
        'image' => '/assets/img/products/Lombo de Meca 1_2-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'lombo_de_pirarucu_700_1500',
        'category' => 'cat_fresh_fish',
        'category_slug' => 'fresh_fish',
        'image' => '/assets/img/products/Lombo de Pirarucu 700_1500-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'lula_em_aneis',
        'category' => 'cat_mollusks',
        'category_slug' => 'mollusks',
        'image' => '/assets/img/products/Lula em aneis-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'mexilhao_limpo',
        'category' => 'cat_mollusks',
        'category_slug' => 'mollusks',
        'image' => '/assets/img/products/Mexilhão Limpo-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'mexilhao_meia_concha',
        'category' => 'cat_mollusks',
        'category_slug' => 'mollusks',
        'image' => '/assets/img/products/Mexilhão meia concha-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'mexilhao_meia_concha',
        'category' => 'cat_mollusks',
        'category_slug' => 'mollusks',
        'image' => '/assets/img/products/Mexilhão meia concha-d.webp',
        'badge' => null,
    ],
    [
        'id' => 'polvo_limpo_e_eviserado_2_3',
        'category' => 'cat_mollusks',
        'category_slug' => 'mollusks',
        'image' => '/assets/img/products/Polvo limpo e eviserado 2_3-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'posta_de_cacao',
        'category' => 'cat_fresh_fish',
        'category_slug' => 'fresh_fish',
        'image' => '/assets/img/products/Posta de cacao-b.webp',
        'badge' => null,
    ],
    [
        'id' => 'veira_20_30_s_coral',
        'category' => 'cat_mollusks',
        'category_slug' => 'mollusks',
        'image' => '/assets/img/products/Veira 20_30 S_coral-b.webp',
        'badge' => null,
    ],
];
